import { extractionComponents, qpcrComponents, tipComponents } from "./catalog";
import type { InventoryItem, Order, Tender } from "./types";

export const fallbackOrders: Order[] = [
  {
    id: "ord-1",
    quotationId: "QT-2601-001",
    partnerCode: "C000013",
    partnerName: "UM Medical Centre",
    invNumber: "INV-10421",
    amount: 18650,
    status: "Pending",
    doDate: null,
    createdAt: "2026-08-18T09:00:00.000Z",
    paymentTerms: "Net 30",
    creditLimit: 80000,
    creditExposure: 22400,
    lines: [
      { skuId: "inv-1", sku: "PH-QPCR-96", name: "Respiratory Panel qPCR Kit", qty: 8 },
      { skuId: "inv-3", sku: "PH-TIP-1K", name: "Filter Tips 200 µL", qty: 4 },
    ],
    dispatchNote: null,
    creditVerified: false,
    inventoryLocked: false,
  },
  {
    id: "ord-2",
    quotationId: "QT-2601-014",
    partnerCode: "C000600",
    partnerName: "Hospital Sultanah Aminah",
    invNumber: "INV-10488",
    amount: 43200,
    status: "Partial Delivery",
    doDate: "2026-08-20",
    createdAt: "2026-08-12T04:30:00.000Z",
    paymentTerms: "LC 60",
    creditLimit: 120000,
    creditExposure: 43200,
    lines: [
      { skuId: "inv-2", sku: "PH-EXT-96", name: "Viral RNA Extraction Kit", qty: 12 },
    ],
    dispatchNote: "DN-20260820-002",
    creditVerified: true,
    inventoryLocked: true,
  },
  {
    id: "ord-3",
    quotationId: "QT-2608-072",
    partnerCode: "C000241",
    partnerName: "IMR Kuala Lumpur",
    invNumber: "INV-10502",
    amount: 9780,
    status: "Approved",
    doDate: "2026-08-22",
    createdAt: "2026-08-21T02:15:00.000Z",
    paymentTerms: "Net 45",
    creditLimit: 40000,
    creditExposure: 9780,
    lines: [
      { skuId: "inv-1", sku: "PH-QPCR-96", name: "Respiratory Panel qPCR Kit", qty: 4 },
    ],
    dispatchNote: "DN-20260822-003",
    creditVerified: true,
    inventoryLocked: true,
  },
];

export const fallbackInventory: InventoryItem[] = [
  {
    id: "inv-1",
    sku: "PH-QPCR-96",
    name: "Respiratory Panel qPCR Kit",
    brand: "Thermo Fisher",
    supplier: "Thermo Fisher Scientific (M) Sdn Bhd",
    supplierEmail: "orders.my@thermofisher.example",
    quantity: 14,
    reorderPoint: 20,
    unit: "kits",
    kitSize: 96,
    formulation: [
      {
        label: "Kit size",
        value: "96 reactions",
        hint: "One 96-sample kit covers a full PCR plate including NTC and positive controls.",
      },
      {
        label: "Master mix",
        value: "12.5 µL / rxn",
        hint: "2× qPCR master mix. Scale to 1,320 µL for 96 wells plus 10% overage.",
      },
      {
        label: "Primer / probe",
        value: "2.5 µL / rxn",
        hint: "10× working mix at 400 nM primers and 200 nM probe.",
      },
    ],
    components: qpcrComponents,
    lastLot: "TF-2607-Q96",
    lastBatchQty: 20,
  },
  {
    id: "inv-2",
    sku: "PH-EXT-96",
    name: "Viral RNA Extraction Kit",
    brand: "QIAGEN",
    supplier: "QIAGEN Malaysia Sdn Bhd",
    supplierEmail: "supply.my@qiagen.example",
    quantity: 36,
    reorderPoint: 24,
    unit: "kits",
    kitSize: 96,
    formulation: [
      {
        label: "Kit size",
        value: "96 samples",
        hint: "96 spin columns, collection tubes, and lysis buffer for one full plate.",
      },
      {
        label: "Lysis buffer",
        value: "560 µL / sample",
        hint: "Includes carrier RNA. Pre-warm to 56°C if precipitate is visible.",
      },
    ],
    components: extractionComponents,
    lastLot: "QG-2606-E96",
    lastBatchQty: 24,
  },
  {
    id: "inv-3",
    sku: "PH-TIP-1K",
    name: "Filter Tips 200 µL",
    brand: "Pigeon Labs",
    supplier: "Pigeon Labs OEM",
    supplierEmail: "procurement@pigeonhub.example",
    quantity: 8,
    reorderPoint: 12,
    unit: "racks",
    kitSize: null,
    formulation: [
      {
        label: "Format",
        value: "96-tip rack",
        hint: "Sterile aerosol-resistant tips for 96-channel heads.",
      },
    ],
    components: tipComponents,
    lastLot: "PL-2608-T200",
    lastBatchQty: 10,
  },
];

const mohCompliance = [
  { id: "mof", label: "MOF ePerolehan registration", done: true },
  { id: "mda", label: "MDA product registration (IVD)", done: true },
  { id: "bg", label: "Banker's guarantee 2.5%", done: false },
  { id: "sst", label: "SST-02 current filing", done: true },
  { id: "iso", label: "ISO 13485 / GDPMD", done: false },
];

export const fallbackTenders: Tender[] = [
  {
    id: "tnd-1",
    reference: "MOH-TDR-2026-441",
    buyer: "Ministry of Health",
    title: "National qPCR consumables framework",
    valueRm: 1280000,
    estimatedCogs: 896000,
    status: "Submitted",
    dueDate: "2026-09-04",
    compliance: mohCompliance,
  },
  {
    id: "tnd-2",
    reference: "UM-RFQ-8891",
    buyer: "Universiti Malaya",
    title: "Teaching lab extraction kits (FY26)",
    valueRm: 96500,
    estimatedCogs: 57900,
    status: "Draft",
    dueDate: "2026-08-29",
    compliance: [
      { id: "sst", label: "SST-02 current filing", done: true },
      { id: "iso", label: "ISO 13485 / GDPMD", done: true },
      { id: "coa", label: "Lot COA pack attached", done: false },
    ],
  },
];
